<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDSgmns5\Api_Console_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDSgmns5/Api_Console_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDSgmns5.legacy');

    return;
}

if (!\class_exists(Api_Console_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDSgmns5\Api_Console_KernelDevDebugContainer::class, Api_Console_KernelDevDebugContainer::class, false);
}

return new \ContainerDSgmns5\Api_Console_KernelDevDebugContainer([
    'container.build_hash' => 'DSgmns5',
    'container.build_id' => 'd66ba5fe',
    'container.build_time' => 1716837797,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDSgmns5');
